Add deployment of repo to 'repo' branch Generate repo data based on new config.json file Use github workflows to buid repo Only deploy plugins if prevous job was successful Only run workflow on PRs to the 'official' and 'master' branches, but run it on commits to all branches Only push repo on commits to 'master' or 'official' branches Import generator script from template branch so the man branch can be clean of repo building code

diff --git a/.github/workflows/plugin-checker.yml b/.github/workflows/plugin-checker.yml
--- a/.github/workflows/plugin-checker.yml
+++ b/.github/workflows/plugin-checker.yml
@@ -7,6 +7,7 @@ on:
   pull_request:
     branches:
       - 'official'
+      - 'master'
 
 jobs:
 
@@ -29,6 +30,7 @@ jobs:
     # |_____|_| |_|___/\__,_|_|  \___| |_|   |_|  \___||___/\___|_| |_|\__|
     #                                                                      
     - name: Check .gitignore in all plugin folders
+      if: success() || failure()
       run: |
         success=0
         for plugin_dir in source/*; do
@@ -46,6 +48,7 @@ jobs:
             exit 1
         fi
     - name: Check info.json in all plugin folders
+      if: success() || failure()
       run: |
         success=0
         for plugin_dir in source/*; do
@@ -63,6 +66,7 @@ jobs:
             exit 1
         fi
     - name: Check plugin.py in all plugin folders
+      if: success() || failure()
       run: |
         success=0
         for plugin_dir in source/*; do
@@ -87,6 +91,7 @@ jobs:
     # |_____|_| |_|___/\__,_|_|  \___| |_|  |_|_|___/___/_|_| |_|\__, |
     #                                                            |___/ 
     - name: Check site-packages in all plugin folders
+      if: success() || failure()
       run: |
         success=0
         for plugin_dir in source/*; do
@@ -104,6 +109,7 @@ jobs:
             exit 1
         fi
     - name: Check settings.json in all plugin folders
+      if: success() || failure()
       run: |
         success=0
         for plugin_dir in source/*; do
@@ -121,18 +127,68 @@ jobs:
             exit 1
         fi
 
+    # Store success message in success file artifact
+    - name: Set success file on completion of tests
+      if: success()
+      run: echo 'true' > success_file.txt
+    - name: Upload success file
+      if: success()
+      uses: actions/upload-artifact@v1
+      with:
+        name: success_file
+        path: success_file.txt
+
   # Build the plugin repository
   deploy-plugin-repo:
+    needs: [plugins-contain-require-files]
     runs-on: ubuntu-latest
     name: Build the plugin repository
     steps:
 
+    # Fetch and read sucess file
+    - name: Download success file from previous job
+      uses: actions/download-artifact@v2
+      with:
+        path: ./artifacts/
+    - name: Read success file
+      id: previous_jobs_success
+      run: |
+        IS_SUCCESS=$(cat ./artifacts/success_file/success_file.txt)
+        echo ::set-output name=IS_SUCCESS::${IS_SUCCESS}
+        rm -rfv ./artifacts
+
     # Checkout
     - name: Checkout
+      if: steps.previous_jobs_success.outputs.IS_SUCCESS == 'true'
       uses: actions/checkout@v2
+
+    # Ensure repo is checked out
+    - name: Check repo for config file
+      if: success()
+      id: ensure_repo
+      run: |
+        if [ ! -e ./config.json ]; then
+            echo "Unable to build repo. Was not checked out."
+            exit 1
+        fi
+
+    # Import scripts from template branch
+    - name: Pull in scripts from template branch
+      if: success()
+      id: read_template_tree
+      run: |
+        git fetch origin template
+        git read-tree --prefix=template -u origin/template
+        cp -rf ./template/scripts ./
+        git rm -r --cached template
+        if [ ! -e ./scripts/generate_repository.py ]; then
+            echo "Unable to build repo. Could not find generator script."
+            exit 1
+        fi
 
     # Setup python environment
     - name: Set up Python 3.8
+      if: success()
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
@@ -142,4 +198,15 @@ jobs:
       if: success()
       id: generate_repo
       run: |
-        python ./generate_repository.py
+        python ./scripts/generate_repository.py
+
+    # Deploy to repo branch
+    - name: Deploy repository
+      if: success() && (github.ref == 'refs/heads/master')
+      uses: s0/git-publish-subdir-action@develop
+      env:
+        REPO: self
+        BRANCH: repo
+        FOLDER: repo
+        SQUASH_HISTORY: true
+        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
